apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "kong-template-github-dbless-ba-45"
  annotations:
    github.com/project-slug: sandrojrcorp/kong-template-github-standard-45
    backstage.io/techdocs-ref: dir:.
    vault.io/secrets-path: devportal
spec:
  type: devops
  lifecycle: experimental
  owner: "group:default/admin"
